server:
  port: 8081
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual # MANUAL:手动处理 AUTO:自动处理
    # NONE值是禁用发布确认模式，是默认值
    # CORRELATED值是发布消息成功到交换器后会触发回调方法，如1示例
    # SIMPLE值经测试有两种效果，
    # 其一效果和CORRELATED值一样会触发回调方法，
    # 其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，根据返回结果来判定下一步的逻辑，
    # 要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，则接下来无法发送消息到broker;
    publisher-confirm-type: correlated #消息确认机制
    publisher-returns: true # 消息回退确认机制
    host: 192.168.2.110
    port: 5672
    username: guest
    password: guest
    virtual-host: my_test
