
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.2.110:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 50
    packages:
      trust-all: true   #是否信任所有包，信任后所有包内的对象均可序列化传输
#  发布订阅 配置
  jms:
    pub-sub-domain: true