
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  quartz:
    job-store-type: JDBC #数据库存储quartz任务配置
    jdbc:
      initialize-schema: NEVER #自动初始化表结构，第一次启动的时候这里写always




thread-pool:
  enable: true
  poolLists:
    - poolId: test    #线程池唯一标识
      poolName: 测试1   #线程池的中文描述，比如线程池给谁用？
      coreSize: 5  #线程池初始化核心线程数量
      maxSize: 10  #线程池最大线程容量
      queueCapacity: 10  #线程池等待队列的容量
    - poolId: test2
      poolName: 测试2
      coreSize: 5
      maxSize: 10
      queueCapacity: 10