## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  elasticsearch:
    rest:
      uris: 192.168.2.110:9200
## Mybatis 配置
mybatis:
  typeAliasesPackage: com.dyq.springboot.elasticsearch.document
  mapperLocations: classpath:mapper/*.xml


